name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ensure this matches your Azure runtime stack

      - name: Install dependencies
        run: |
          cd app  # Navigate to your FastAPI app directory
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your FastAPI dependencies

      - name: Publish to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: BookfastApi  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Add your publish profile secret
          package: .  # Package the current directory
