name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust based on your Python version

      - name: Install dependencies
        run: |
          cd app  # Navigate to your FastAPI app directory
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you have different requirements

      - name: Build Frontend
        run: |
          cd frontend  # Navigate to your frontend directory
          npm install  # Install frontend dependencies
          npm run build  # Build the frontend application

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /frontend       # Path to your frontend application
          api_location: /app            # Path to your FastAPI app
          app_build_command: npm run build  # Command to build the frontend
          output_location: /frontend/build   # Path to the build output
